name: pull requests tests

on:
  pull_request:

jobs:
  ci:
    runs-on: ubuntu-latest
    
    steps:
      - uses: docker-practice/actions-setup-docker@master
        timeout-minutes: 12

      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.20
          check-latest: true
          cache: true
          
      - name: Check Go code formatting
        run: make db_up

      - name: Run tests
        run: go test -v ./tests/...
